### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by sameterduren** [mateogianolio/matplotnode#1]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'matplotnode' ]
2 info using npm@2.15.9
3 info using node@v4.5.0
4 verbose stack SyntaxError: Error parsing C:\Program Files\nodejs\node_modules\npm\node_modules\request\node_modules\har-validator\node_modules\is-my-json-valid\node_modules\generate-object-property\node_modules\is-property\package.json: Unexpected end of input
4 verbose stack     at Object.parse (native)
4 verbose stack     at readPackage (module.js:81:52)
4 verbose stack     at tryPackage (module.js:91:13)
4 verbose stack     at Function.Module._findPath (module.js:153:20)
4 verbose stack     at Function.Module._resolveFilename (module.js:323:25)
4 verbose stack     at Function.Module._load (module.js:276:25)
4 verbose stack     at Module.require (module.js:353:17)
4 verbose stack     at require (internal/module.js:12:17)
4 verbose stack     at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\node_modules\har-validator\node_modules\is-my-json-valid\node_modules\generate-object-property\index.js:1:80)
4 verbose stack     at Module._compile (module.js:409:26)
5 verbose cwd C:\Users\SZI\Desktop\matplotnode-master\matplotnode-master
6 error Windows_NT 6.1.7601
7 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "matplotnode"
8 error node v4.5.0
9 error npm  v2.15.9
10 error path C:\Program Files\nodejs\node_modules\npm\node_modules\request\node_modules\har-validator\node_modules\is-my-json-valid\node_modules\generate-object-property\node_modules\is-property\package.json
11 error Error parsing C:\Program Files\nodejs\node_modules\npm\node_modules\request\node_modules\har-validator\node_modules\is-my-json-valid\node_modules\generate-object-property\node_modules\is-property\package.json: Unexpected end of input
12 error If you need help, you may report this error at:
12 error     https://github.com/npm/npm/issues
13 verbose exit [ 1, true ]

**Comment by mateogianolio** [comment]
Are you sure you have Python 2.7 [1] and matplotlib [2] installed?
1. https://www.python.org/downloads/
2. http://matplotlib.org/users/installing.html#windows
